# Generated by Django 3.1 on 2020-08-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200815_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(default=0, help_text='Будет показываться в карточке новости', max_length=300, verbose_name='Введение'),
            preserve_default=False,
        ),
    ]
