# Generated by Django 3.1 on 2020-08-12 17:32

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('home', '0004_auto_20200812_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.StreamField([('Заголовок', wagtail.core.blocks.CharBlock(classname='full title')), ('Страница', wagtail.core.blocks.PageChooserBlock(required=False))], verbose_name='Тело страницы')),
            ],
            options={
                'verbose_name': 'Страница с ссылками',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='otherpage',
            name='body',
        ),
    ]
