# Generated by Django 3.1 on 2020-08-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepageslideritem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageSliderItem',
        ),
    ]
