# Generated by Django 3.1 on 2020-08-16 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0009_homepage_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='main_image',
        ),
        migrations.AddField(
            model_name='homepage',
            name='carousel_image_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение для карусели 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='carousel_image_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение для карусели 2'),
        ),
    ]
