# Generated by Django 3.1 on 2020-08-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_formfield_formpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpage',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='to_address',
        ),
    ]
